version: '3.9'

services:

  db-ms-sales:
    image: postgres
    restart: always
    container_name: db-ms-sales
    environment:
      POSTGRES_DB: $ENV_DB_MS_SALES_POSTGRES_DB
      POSTGRES_USER: $ENV_DB_MS_SALES_POSTGRES_USER
      POSTGRES_PASSWORD: $ENV_DB_MS_SALES_POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./ms-sales/db/scripts/:/docker-entrypoint-initdb.d
      - db-ms-sales:/var/lib/postgresql/data
    networks:
      - microservices-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    command: [ nginx, '-g', 'daemon off;' ]
    restart: on-failure
    ports:
      - '80:80'
    #volumes:
      #- ./nginx/:/etc/nginx
    networks:
      - microservices-network

  ms-sales:      
    build: 
      context: ./ms-sales
      args:
        - JAR_NAME=ms-sales-0.0.1-SNAPSHOT
    container_name: ms-sales
    environment:
      - APP_PORT=8080
      - DB_URL=jdbc:postgresql://db-ms-sales:5432/sales
      - DB_USERNAME=$ENV_DB_MS_SALES_POSTGRES_USER
      - DB_PASSWORD=$ENV_DB_MS_SALES_POSTGRES_PASSWORD
      - ACTIVE_PROFILE=prod
    #ports:
     # - 8081:8080
    networks:
      - microservices-network
    depends_on:
      - db-ms-sales


networks:
  microservices-network:
    driver: bridge
    name: microservices-network

volumes:
  db-ms-sales:
    name: db-ms-sales  
