apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Name }}
  labels:
    app: {{.Release.Name }}
spec:
  storageClassName: {{.Values.volume.storageClassName }}
  capacity:
    storage: {{.Values.volume.capacity.storage }}
  accessModes:
    - "{{.Values.volume.accessModes }}"
  hostPath:
    path: {{.Values.volume.hostPath.path }}