apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name }}
  labels:
    app: {{.Release.Name }}
spec:
  storageClassName: {{.Values.volume.storageClassName }}
  accessModes:
    - "{{.Values.volume.accessModes }}"
  resources:
    requests:
      storage: {{.Values.volume.capacity.storage }}